app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager
# from datetime import datetime 

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))  

class User(UserMixin, db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255),index = True)
    email = db.Column(db.String(255),unique = True,index = True)
    profile_pic_path = db.Column(db.String())
    password_hash = db.Column(db.String(255))
    pass_secure = db.Column(db.String(255))
    post=db.relationship('Post',backref='user',lazy='dynamic')
    comments=db.relationship('Comment',backref='user',lazy='dynamic')

    def __repr__(self):
        return f'User {self.name}'

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)

    def __repr__(self):
        return f'User {self.username}'

    
class Post(db.Model):
    __tablename__ = 'post'

    id = db.Column(db.Integer,primary_key = True)
    post = db.Column(db.String)
    category = db.Column(db.Integer)
    description = db.Column(db.String(255))
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))
    comments = db.relationship('Comment',backref = 'post',lazy="dynamic")

    def save_post(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_all_post(cls):
        
        return Post.query.all()
    
class Comment(db.Model):
    __tablename__ = 'comment'

    id = db.Column(db.Integer,primary_key = True)
    comment = db.Column(db.String(255))
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'))
    post_id = db.Column(db.Integer,db.ForeignKey('post.id'))


    def __repr__(self):
        return f'User {self.name}'
    
    def save_comment(self):
            db.session.add(self)
            db.session.commit()

    def delete_comment(self):
       db.session.delete(self)
       db.session.commit()
   
    @classmethod
    def get_all_comments(cls):
        return comment.query.all

class Profile(db.Model):
    
    __tablename__ ='post_profile'

    id = db.Column(db.Integer, primary_key=True)
    description = db.Column(db.String(255))

    def save_profile(self):
        
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_all_profile(cls):
        
        return Post.query.all()

class Quote:
    def __init__(self,id,author,quote):
        self.id =id
        self.author = author
        self.quote = quote

class Subscribe(db.Model):
    __tablename__ = 'subscribers'
    id = db.Column(db.Integer,primary_key = True)
    email = db.Column(db.String(255),unique = True,index = True)
    def __repr__(self):
        return f'User {self.email}'

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,ValidationError
from wtforms.validators import Required,Email
from ..models import User,Post,Comment

class PostForm(FlaskForm):
    post=  TextAreaField('Post ', validators=[Required()])
    description = TextAreaField('description ', validators=[Required()])
    submit = SubmitField('Submit')
    
class UpdatePostForm(FlaskForm):
    content=TextAreaField('Update Content',validators = [Required()])
    submit=SubmitField('SUBMIT')

class CommentForm(FlaskForm):
    comment = TextAreaField('username comment', validators=[Required()])
    submit = SubmitField('Submit')

class SubForm(FlaskForm):
    email = TextAreaField('input your email', validators=[Required()])
    submit = SubmitField('Submit')



class UpdateProfile(FlaskForm):
    description = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail


login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db = SQLAlchemy()
photos = UploadSet('photos',IMAGES)
mail = Mail()
  
def create_app(config_name):

    app = Flask(__name__)

    # Creating the app configurations

    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    
    # setting config

    from .request import configure_request
    configure_request(app)

    # configure UploadSet
    configure_uploads(app,photos)
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/authenticate')

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,error

app/main/views.py
from flask import render_template,redirect,url_for,abort
from . import main
from .forms import UpdateProfile,CommentForm,PostForm,SubForm,UpdatePostForm
from ..models import User,Post,Comment,Subscribe
from flask_login import login_required,current_user
from .. import db,photos
from ..request import get_quote
from ..email import mail_message



@main.route('/')
def index():
    title = 'Home - Welcome to The best Post Website Online'
    quote=get_quote()
    all_post = Post.get_all_post()
    return render_template('index.html', title = title, all_post=all_post, quote=quote)

@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)
        db.session.add(user)
        db.session.commit()
    return render_template("profile/profile.html", user = user)   

@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.description = form.description.data

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)


@main.route('/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()

    if form.validate_on_submit():
        post = form.post.data
        description = form.description.data
        new_post = Post(post =post , description = description)
        new_post.save_post()
        return redirect(url_for('.index'))
    return render_template('new_post.html', post_form=form)

@main.route('/comment/<int:id>',methods = ['GET','POST'])
@login_required
def new_comment(id):
    form = CommentForm()
    imishwi =Comment.query.filter_by(post_id = id).all()
    if form.validate_on_submit():
        comment = form.comment.data
        new_comment = Comment(comment = comment , post_id=id, user=current_user)
        new_comment.save_comment()
        return redirect(url_for('.new_comment',id=id))
    return render_template('new_comment.html', imishwi=imishwi,comment_form=form)


@main.route('/delete/comment/<int:id>' , methods = ['GET', 'POST']) 
def delete_comment(id):
    imishwi =Comment.query.filter_by(post_id = id).first()
    imishwiform=CommentForm()  
    if imishwi is not None:
        imishwi.delete_comment()

        return redirect(url_for('main.index'))
    return render_template('new_comment.html',imishwiform=imishwiform)


@main.route('/edit/post/<int:id>',methods= ['GET','POST'])
@login_required
def update_post(id):
   post=Post.query.filter_by(id=id).first()
   if post is None:
        abort(404)

   form=UpdatePostForm()
   if form.validate_on_submit():
         post.description=form.content.data
         db.session.add(post)
         db.session.commit()

         return redirect(url_for('main.index'))
   return render_template('update_post.html',form=form)

@main.route('/subscribe', methods=['GET','POST'])
def subscribe():
    sub_form=SubForm()
    if sub_form.validate_on_submit():
        email=sub_form.email.data
        new_subscriber=Subscribe(email=email)

        db.session.add(new_subscriber)
        db.session.commit()
        mail_message("you are welcome","email/welcome_subscribe",new_subscriber.email)
        
        return redirect(url_for('main.index'))

    return render_template('subscribe.html',sub_form =sub_form)

app/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        {% if title %}
            <title> {{ title }}</title>
            {% else %}
            <title> Welcome to the personnel blog website </title>
        {% endif %} 
        {% extends 'bootstrap/base.html'%}
        {% block navbar %}
            {% include 'navbar.html' %}
        {% endblock %}
    </head>
    <body>
        {% block content %}
        
        {% endblock%}
    </body>
</html>

app/templates/fourOwfour.html
 {% extends 'base.html'%}

{% block content %}
    <h1>WHOOOPS we can't find that page</h1>
{% endblock %}

app/templates/index.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}
<!-- Styles block -->
{% block content %}
    <div style="background-color:burlywood;">
        <div style=" margin-right:100px;margin-left: 100px;text-align:center; font-size:6px;">
            <span style="font-size:60px; font-family: 'Akronim', cursive;">PERSONAL-BLOG-WEBSITE</span>
       </div>
        <div class="panel" style=" border: 3px solid #f2f2f2; margin-top:10px; padding:20px; margin-left: 100px;margin-right: 100px;">
            <p style="font-family: 'Bellefair', serif; font-size:25px;">If you won't to add pitches,first sign up and then continue,please also feel free to comment</p>
            <div style="text-align:center; font-size: 25px;">
                <a href="/new">
                    <br>
                    <span >Add a new Post</span>
                </a>
            </div>
        </div> 
        
        <blockquote class="panel" style="border: 3px solid #f2f2f2; margin-top:10px; margin-right:100px; margin-left: 100px;">
            <h2>Random quote</h2>
            <p>{{quote.quote}}</p>
            <p>Aouthor:{{quote.quote}}</p>
        </blockquote>

        <div class="panel" style=" border: 3px solid #f2f2f2; margin-top:10px; padding:20px; margin-left: 100px;margin-right: 100px; text-align:center;">
            {%for dodo in all_post%}
            <p>{{dodo.description}}</p>
            <a href="/comment/{{dodo.id}}" ><button>comment</button></a>
            <a href="/edit/post/{{dodo.id}}"><button>Edit</button></a>
            <a href="/delete/comment/{{dodo.id}}"><button>Delete</button></a>
            {%endfor%}
        </div>
        
    </div>
        
           
            
    <div class="row">
            
      {{macro.displayPostList(post_list)}}
    </div>  

    
{% endblock %}

app/templates/macros.html
{% macro displayPostList(post_list) %} 
{% for post in post_list %}
<!-- <div class="col-xs-6 col-sm-6 col-md-6">
  <div class="card m-2">
    <div class="card-header">
      Category - {{post.category}}
    </div>
    <div class="card-body">
      <p class="card-text">{{post.category}}</p>
      <p class="card-text">{{post.Description}}</p>
      <p class="card-text"><small class="text-muted">{{post.post}}</small></p>
      <hr>
      <p>Add a comment <a href="/comment/{{post.id}}">here</a>.</p>
    </div>
  </div>
</div> -->
{% endfor %}
{% endmacro %}

  

app/templates/navbar.html
 <div class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"> Blog </a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">Home</a></li>
            </ul>
            <ul class="nav navbar-nav">
                <li><a href="{{url_for('main.subscribe')}}">Subscribe</a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
                <li style="color:white;padding:15px;">{{current_user.username}}</li>
                <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
                {% else %}
                <li><a href="{{url_for('auth.login')}}">Sign in</a></li>

                {%endif%}
            </ul>
        </div>
    </div>
</div>

app/templates/new_comment.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container" >
    <a href="{{url_for('main.index')}}">
            <button type="button" class="btn btn-primary btn-sm" style="margin-bottom:10px;">
                <span class="glyphicon glyphicon-chevron-left" ></span> Back
            </button>
    </a>
            {{wtf.quick_form(comment_form)}}

            {%for dada in imishwi%}
                <p>{{dada.comment}}</p>
                <a href="/delete/comment/{{dada.id}}"><button>delete-comment</button></a>
            {%endfor%}

</div>
{% endblock %}

app/templates/new_pitch.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container" >
    <a href="{{url_for('main.index')}}">
            <button type="button" class="btn btn-primary btn-sm" style="margin-bottom:10px;">
                    <span class="glyphicon glyphicon-chevron-left" ></span> Back
            </button>
    </a>
   
    {{wtf.quick_form(post_form)}}

</div>
{% endblock %}

app/templates/new_post.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container" >
    <a href="{{url_for('main.index')}}">
            <button type="button" class="btn btn-primary btn-sm" style="margin-bottom:10px;">
                    <span class="glyphicon glyphicon-chevron-left" ></span> Back
            </button>
    </a>
   
    {{wtf.quick_form(post_form)}}

</div>
{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
  <div class="container">
      <a href="{{url_for('main.index')}}">
          <button type="button" class="btn btn-primary btn-sm" style="margin-bottom:10px;">
              <span class="glyphicon glyphicon-chevron-left" ></span> Back
          </button>
      </a>

    <div class="row">
              <!-- displaying  Username-->
      <div class="col-md-4">
          <h3> {{user.username| capitalize}} </h3>

          <!--Displaying user description-->
          {% if user.description %}
            <p> {{user.description}}</p>
          {% endif %}

          {% if user == current_user %}
            <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
          {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}

app/templates/subscribe.html
{% extends 'base.html'%}

{% import "bootstrap/wtf.html" as wtf %}
    {% block content %}
    <div class="container">

        <div>
            {{wtf.quick_form(sub_form)}}
        </div>
    </div>
    {% endblock%}

app/templates/update_post.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}
{% import "bootstrap/wtf.html" as wtf %}
{% block styles%}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{% endblock %}

{% block content %}
<div class="container"> 
    {{wtf.quick_form(form)}}

</div>

{% endblock %}